# Generated by Django 5.0.5 on 2024-05-12 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worth_it', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accuracy', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('delivery', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('orders_complete', models.IntegerField(db_default=0, null=True)),
                ('products', models.IntegerField(db_default=0, null=True)),
                ('reviews_count', models.IntegerField(db_default=0, null=True)),
                ('address', models.SlugField()),
                ('preview', models.ImageField(db_default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/kates.png', default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/kates.png', upload_to='')),
                ('views_count', models.IntegerField(db_default=0, default=0)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.review')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('product_description', models.TextField()),
                ('key_features', models.TextField()),
                ('preview', models.ImageField(default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/default_product_view.jpeg', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.categories')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.review')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop')),
            ],
        ),
    ]
