# Generated by Django 5.0.5 on 2024-05-12 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_shop_orders_complete_remove_shop_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/default_product_view.jpeg', upload_to='media/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='delivery',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='worth_it',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='preview',
            field=models.ImageField(db_default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/kates.png', default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/kates.png', upload_to='media/<django.db.models.fields.CharField>/'),
        ),
    ]
