# Generated by Django 5.0.5 on 2024-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_product_preview_alter_review_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='preview',
            field=models.ImageField(db_default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/kates.png', default='/Users/danya/CodeProject/djangoMarketPlace/static/img/catalog/kates.png', upload_to='media/shops/<django.db.models.fields.CharField>/'),
        ),
    ]
