# Generated by Django 5.0.5 on 2024-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.SlugField(unique=True),
        ),
    ]
