# Generated by Django 5.0.5 on 2024-06-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_country_order_name_alter_cart_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart', verbose_name='cart_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
