# Generated by Django 5.0.5 on 2024-06-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
