# Generated by Django 5.0.5 on 2024-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_cart_order_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
