# Generated by Django 5.0.5 on 2024-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_cart_product_remove_order_cart_id_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
